### ISSUE TITLE
 kubectl cluster-info is failing after cfcr deployment.

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry-incubator/cfcr-home#3]
why is this below exception ?

Unable to connect to the server: x509: certificate is valid for 10.100.200.1, not 10.x.x.161
[root@PPC_CentOS7 bin]# kubectl get pods --namespace=kube-system

**Comment by techie20122018** [comment]
Any suggestion on this issue ?

**Comment by jhvhs** [comment]
Hi @techie20122018 ,

This repo contains developer workstation setup scripts.
You should try asking the [kubernetes community](http://slack.k8s.io/)
providing details on the cluster configuration, and how the cluster was installed.
