### ISSUE TITLE
Unable to connect to the server: EOF in cfcr

### ISSUE THREAD

**Issue by techie20122018** [cloudfoundry-incubator/cfcr-home#4]
[root@CentOS7 kubo-deployment]# kubectl get pods --namespace=kube-system
Unable to connect to the server: EOF

I am seeing the port 8080 active in master . But still I am unable to telnet in that port. getting above exception.

Thx

**Comment by jhvhs** [comment]
Hi @techie20122018 ,

This repo contains developer workstation setup scripts and has nothing
to do with CFCR itself.
You should try asking the [kubernetes community](http://slack.k8s.io/)
providing details on the cluster configuration, and how the cluster was installed.
If you think your question is related to CFCR, you can ask it on the #cfcr
slack channel  on https://slack.cloudfoundry.org
